CREATE TABLE ESTOQUE (
    ESTOQUE_ID bigint not null auto_increment,
    TIPO_SANGUE int not null unique,
    QUANTIDADE int not null,

    primary key (ESTOQUE_ID)
);

INSERT INTO ESTOQUE ( TIPO_SANGUE, QUANTIDADE) VALUES (0, 134);
INSERT INTO ESTOQUE (TIPO_SANGUE, QUANTIDADE) VALUES (1, 32);
INSERT INTO ESTOQUE (TIPO_SANGUE, QUANTIDADE) VALUES (2, 52);
INSERT INTO ESTOQUE (TIPO_SANGUE, QUANTIDADE) VALUES (3, 12);
INSERT INTO ESTOQUE (TIPO_SANGUE, QUANTIDADE) VALUES (4, 12);
INSERT INTO ESTOQUE (TIPO_SANGUE, QUANTIDADE) VALUES (5, 7);
INSERT INTO ESTOQUE (TIPO_SANGUE, QUANTIDADE) VALUES (6, 4);
INSERT INTO ESTOQUE (TIPO_SANGUE, QUANTIDADE) VALUES (7, 5);